CREATE TABLE IF NOT EXISTS routing_profiles (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    server_id BIGINT UNSIGNED NOT NULL,
    name VARCHAR(255) NOT NULL DEFAULT 'default',
    description TEXT NULL,
    is_active TINYINT(1) NOT NULL DEFAULT 1,
    direct_ipset_name VARCHAR(64) NOT NULL DEFAULT 'direct_ip',
    upstream_ipset_name VARCHAR(64) NOT NULL DEFAULT 'niderland_ip',
    no_quic_ipset_name VARCHAR(64) NOT NULL DEFAULT 'no_quic',
    direct_route_name VARCHAR(64) NOT NULL DEFAULT 'openmail',
    upstream_route_name VARCHAR(64) NOT NULL DEFAULT 'niderland',
    upstream_interface VARCHAR(64) NOT NULL DEFAULT 'awg2',
    upstream_table_name VARCHAR(64) NOT NULL DEFAULT 'awg2',
    upstream_table_id INT NOT NULL DEFAULT 200,
    upstream_fwmark VARCHAR(16) NOT NULL DEFAULT '0x2',
    upstream_rule_priority INT NOT NULL DEFAULT 1000,
    vpn_input_interface VARCHAR(64) NOT NULL DEFAULT 'amn0',
    dnsmasq_port INT NOT NULL DEFAULT 5353,
    dnsmasq_config_path VARCHAR(255) NOT NULL DEFAULT '/etc/dnsmasq.d/amnyam-routing.conf',
    ipset_persistent_path VARCHAR(255) NOT NULL DEFAULT '/etc/ipset.rules',
    snapshot_base_dir VARCHAR(255) NOT NULL DEFAULT '/root/amnyam-routing-snapshots',
    enabled TINYINT(1) NOT NULL DEFAULT 1,
    created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_routing_profiles_server_id (server_id),
    INDEX idx_routing_profiles_active (server_id, is_active)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS routing_domain_rules (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    profile_id BIGINT UNSIGNED NOT NULL,
    domain VARCHAR(255) NOT NULL,
    match_type ENUM('exact', 'suffix') NOT NULL DEFAULT 'suffix',
    add_to_direct TINYINT(1) NOT NULL DEFAULT 0,
    add_to_upstream TINYINT(1) NOT NULL DEFAULT 0,
    add_to_no_quic TINYINT(1) NOT NULL DEFAULT 0,
    enabled TINYINT(1) NOT NULL DEFAULT 1,
    priority INT NOT NULL DEFAULT 100,
    comment TEXT NULL,
    created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uniq_routing_domain_rule (profile_id, domain, match_type),
    INDEX idx_routing_domain_rules_profile_id (profile_id),
    INDEX idx_routing_domain_rules_domain (domain),
    INDEX idx_routing_domain_rules_enabled (profile_id, enabled)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS routing_ip_sources (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    profile_id BIGINT UNSIGNED NOT NULL,
    name VARCHAR(255) NOT NULL,
    target_ipset ENUM('direct_ip', 'niderland_ip', 'no_quic') NOT NULL,
    source_type ENUM('url_cidr_list', 'url_ip_list') NOT NULL DEFAULT 'url_cidr_list',
    url TEXT NOT NULL,
    enabled TINYINT(1) NOT NULL DEFAULT 1,
    refresh_interval_seconds INT NOT NULL DEFAULT 86400,
    last_loaded_at TIMESTAMP NULL,
    last_status ENUM('never', 'success', 'failed') NOT NULL DEFAULT 'never',
    last_error TEXT NULL,
    last_items_count INT NULL,
    created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_routing_ip_sources_profile_id (profile_id),
    INDEX idx_routing_ip_sources_enabled (profile_id, enabled),
    INDEX idx_routing_ip_sources_target (target_ipset)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS routing_manual_ips (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    profile_id BIGINT UNSIGNED NOT NULL,
    target_ipset ENUM('direct_ip', 'niderland_ip', 'no_quic') NOT NULL,
    value VARCHAR(64) NOT NULL,
    enabled TINYINT(1) NOT NULL DEFAULT 1,
    comment TEXT NULL,
    created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uniq_routing_manual_ip (profile_id, target_ipset, value),
    INDEX idx_routing_manual_ips_profile_id (profile_id),
    INDEX idx_routing_manual_ips_enabled (profile_id, enabled),
    INDEX idx_routing_manual_ips_target (target_ipset)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS routing_upstreams (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    profile_id BIGINT UNSIGNED NOT NULL,
    server_id BIGINT UNSIGNED NOT NULL,
    name VARCHAR(255) NOT NULL DEFAULT 'niderland',
    type ENUM('wireguard_config', 'amneziawg_config') NOT NULL DEFAULT 'amneziawg_config',
    config_content MEDIUMTEXT NOT NULL,
    config_fingerprint CHAR(64) NOT NULL,
    endpoint_host VARCHAR(255) NULL,
    endpoint_port INT NULL,
    client_address VARCHAR(64) NULL,
    enabled TINYINT(1) NOT NULL DEFAULT 1,
    last_applied_at TIMESTAMP NULL,
    last_status ENUM('never', 'success', 'failed') NOT NULL DEFAULT 'never',
    last_error TEXT NULL,
    created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_routing_upstreams_profile_id (profile_id),
    INDEX idx_routing_upstreams_server_id (server_id),
    INDEX idx_routing_upstreams_enabled (profile_id, enabled)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS routing_apply_history (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    profile_id BIGINT UNSIGNED NOT NULL,
    server_id BIGINT UNSIGNED NOT NULL,
    action ENUM('apply', 'warmup', 'check', 'rollback', 'upstream_apply', 'upstream_test') NOT NULL DEFAULT 'apply',
    status ENUM('pending', 'running', 'success', 'failed', 'rolled_back') NOT NULL DEFAULT 'pending',
    domain_checked VARCHAR(255) NULL,
    started_at TIMESTAMP NULL,
    finished_at TIMESTAMP NULL,
    created_by_user_id BIGINT UNSIGNED NULL,
    snapshot_dir VARCHAR(500) NULL,
    stdout MEDIUMTEXT NULL,
    stderr MEDIUMTEXT NULL,
    error_message TEXT NULL,
    created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
    INDEX idx_routing_apply_history_profile_id (profile_id),
    INDEX idx_routing_apply_history_server_id (server_id),
    INDEX idx_routing_apply_history_status (status),
    INDEX idx_routing_apply_history_created_at (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
